# Generated by Django 2.2 on 2020-07-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_book_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_seller_email',
            field=models.CharField(default='jigar93776@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
